import { Profile, VerificationRequest, JobOffer } from './types'

export const CURRENT_USER = {
  id: 'user-1',
  fullName: 'Amadou Diallo',
  title: 'Ingénieur Logiciel Senior',
  email: 'amadou.diallo@email.com',
  city: 'Dakar',
  country: 'Sénégal',
  sector: 'Technologie',
  whatsapp: '+221 77 123 4567',
  contactEmail: 'amadou.diallo@email.com',
  externalLink: 'https://github.com/amadoudiallo',
  languages: ['Français', 'Anglais', 'Wolof'],
  availabilityStatus: 'disponible' as const,
  profileViewsCount: 247,
  publicUrlSlug: 'amadou-diallo',
  verified: true,
  completionPercent: 85,
  skills: [
    { id: 's1', label: 'React' },
    { id: 's2', label: 'Node.js' },
    { id: 's3', label: 'TypeScript' },
    { id: 's4', label: 'PostgreSQL' },
    { id: 's5', label: 'Docker' },
  ],
  experiences: [
    {
      id: 'e1',
      title: 'Ingénieur Logiciel Senior',
      organization: 'Orange Digital Center',
      startDate: '2022-03',
      endDate: null,
      current: true,
      verificationStatus: 'confirmée' as const,
    },
    {
      id: 'e2',
      title: 'Développeur Full Stack',
      organization: 'Teranga Tech',
      startDate: '2019-06',
      endDate: '2022-02',
      current: false,
      verificationStatus: 'confirmée' as const,
    },
    {
      id: 'e3',
      title: 'Développeur Junior',
      organization: 'StartupSN',
      startDate: '2017-09',
      endDate: '2019-05',
      current: false,
      verificationStatus: 'non_demandée' as const,
    },
  ],
  education: [
    {
      id: 'ed1',
      degree: 'Master en Génie Informatique',
      institution: 'École Polytechnique de Thiès',
      startDate: '2015-09',
      endDate: '2017-07',
      current: false,
      verificationStatus: 'en_attente' as const,
    },
    {
      id: 'ed2',
      degree: 'Licence en Informatique',
      institution: 'Université Cheikh Anta Diop',
      startDate: '2012-09',
      endDate: '2015-06',
      current: false,
      verificationStatus: 'confirmée' as const,
    },
  ],
  publications: [
    {
      id: 'p1',
      type: 'article' as const,
      title: 'Optimisation des systèmes distribués en Afrique de l\'Ouest',
      link: 'https://example.com/article1',
    },
  ],
}

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'prof-1',
    userId: 'user-1',
    fullName: 'Amadou Diallo',
    title: 'Ingénieur Logiciel Senior',
    city: 'Dakar',
    country: 'Sénégal',
    sector: 'Technologie',
    languages: ['Français', 'Anglais', 'Wolof'],
    availabilityStatus: 'disponible',
    whatsapp: '+221 77 123 4567',
    contactEmail: 'amadou@email.com',
    externalLink: 'https://github.com/amadoudiallo',
    profileViewsCount: 247,
    publicUrlSlug: 'amadou-diallo',
    verified: true,
    completionPercent: 85,
    skills: [
      { id: 's1', label: 'React' },
      { id: 's2', label: 'Node.js' },
      { id: 's3', label: 'TypeScript' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-2',
    userId: 'user-2',
    fullName: 'Fatou Ndiaye',
    title: 'Consultante Finance & Stratégie',
    city: 'Abidjan',
    country: 'Côte d\'Ivoire',
    sector: 'Finance',
    languages: ['Français', 'Anglais'],
    availabilityStatus: 'en_veille',
    whatsapp: '+225 07 123 4567',
    contactEmail: 'fatou@email.com',
    externalLink: '',
    profileViewsCount: 189,
    publicUrlSlug: 'fatou-ndiaye',
    verified: true,
    completionPercent: 92,
    skills: [
      { id: 's1', label: 'Analyse financière' },
      { id: 's2', label: 'Excel avancé' },
      { id: 's3', label: 'Stratégie' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-3',
    userId: 'user-3',
    fullName: 'Jean-Baptiste Mvondo',
    title: 'Médecin Cardiologue',
    city: 'Douala',
    country: 'Cameroun',
    sector: 'Santé',
    languages: ['Français', 'Anglais'],
    availabilityStatus: 'indisponible',
    whatsapp: '+237 6 12 34 56 78',
    contactEmail: 'jb.mvondo@email.com',
    externalLink: '',
    profileViewsCount: 134,
    publicUrlSlug: 'jb-mvondo',
    verified: true,
    completionPercent: 78,
    skills: [
      { id: 's1', label: 'Cardiologie' },
      { id: 's2', label: 'Échographie' },
      { id: 's3', label: 'Recherche clinique' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-4',
    userId: 'user-4',
    fullName: 'Aïssatou Bah',
    title: 'Avocate en Droit des Affaires',
    city: 'Conakry',
    country: 'Guinée',
    sector: 'Juridique',
    languages: ['Français', 'Anglais', 'Peul'],
    availabilityStatus: 'disponible',
    whatsapp: '+224 6 21 23 45 67',
    contactEmail: 'aissatou.bah@email.com',
    externalLink: 'https://cabinet-bah.com',
    profileViewsCount: 201,
    publicUrlSlug: 'aissatou-bah',
    verified: false,
    completionPercent: 70,
    skills: [
      { id: 's1', label: 'Droit des affaires' },
      { id: 's2', label: 'Contrats' },
      { id: 's3', label: 'OHADA' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-5',
    userId: 'user-5',
    fullName: 'Moussa Traoré',
    title: 'Data Scientist',
    city: 'Bamako',
    country: 'Mali',
    sector: 'Technologie',
    languages: ['Français', 'Anglais', 'Bambara'],
    availabilityStatus: 'disponible',
    whatsapp: '+223 70 12 34 56',
    contactEmail: 'moussa.traore@email.com',
    externalLink: 'https://kaggle.com/moussatraore',
    profileViewsCount: 312,
    publicUrlSlug: 'moussa-traore',
    verified: true,
    completionPercent: 88,
    skills: [
      { id: 's1', label: 'Python' },
      { id: 's2', label: 'Machine Learning' },
      { id: 's3', label: 'SQL' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-6',
    userId: 'user-6',
    fullName: 'Mariama Camara',
    title: 'Directrice Marketing Digital',
    city: 'Paris',
    country: 'France',
    sector: 'Marketing',
    languages: ['Français', 'Anglais'],
    availabilityStatus: 'en_veille',
    whatsapp: '+33 6 12 34 56 78',
    contactEmail: 'mariama.camara@email.com',
    externalLink: 'https://linkedin.com/in/mariama-camara',
    profileViewsCount: 445,
    publicUrlSlug: 'mariama-camara',
    verified: true,
    completionPercent: 95,
    skills: [
      { id: 's1', label: 'SEO/SEA' },
      { id: 's2', label: 'Marketing digital' },
      { id: 's3', label: 'Analytics' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-7',
    userId: 'user-7',
    fullName: 'Kofi Mensah',
    title: 'Architecte & Urbaniste',
    city: 'Accra',
    country: 'Ghana',
    sector: 'Architecture',
    languages: ['Français', 'Anglais', 'Twi'],
    availabilityStatus: 'disponible',
    whatsapp: '+233 20 123 4567',
    contactEmail: 'kofi.mensah@email.com',
    externalLink: 'https://mensah-arch.com',
    profileViewsCount: 156,
    publicUrlSlug: 'kofi-mensah',
    verified: false,
    completionPercent: 65,
    skills: [
      { id: 's1', label: 'AutoCAD' },
      { id: 's2', label: 'BIM' },
      { id: 's3', label: 'Design durable' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-8',
    userId: 'user-8',
    fullName: 'Awa Sow',
    title: 'Enseignante-Chercheuse en Économie',
    city: 'Saint-Louis',
    country: 'Sénégal',
    sector: 'Éducation',
    languages: ['Français', 'Anglais', 'Wolof', 'Pulaar'],
    availabilityStatus: 'en_veille',
    whatsapp: '+221 77 987 6543',
    contactEmail: 'awa.sow@ugb.edu.sn',
    externalLink: 'https://ugb.edu.sn/awa-sow',
    profileViewsCount: 89,
    publicUrlSlug: 'awa-sow',
    verified: true,
    completionPercent: 80,
    skills: [
      { id: 's1', label: 'Économétrie' },
      { id: 's2', label: 'Recherche' },
      { id: 's3', label: 'Enseignement' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-9',
    userId: 'user-9',
    fullName: 'Ibrahim Touré',
    title: 'Responsable RH & Talent Acquisition',
    city: 'Lomé',
    country: 'Togo',
    sector: 'Ressources Humaines',
    languages: ['Français', 'Anglais', 'Éwé'],
    availabilityStatus: 'disponible',
    whatsapp: '+228 90 12 34 56',
    contactEmail: 'ibrahim.toure@email.com',
    externalLink: '',
    profileViewsCount: 278,
    publicUrlSlug: 'ibrahim-toure',
    verified: true,
    completionPercent: 90,
    skills: [
      { id: 's1', label: 'Recrutement' },
      { id: 's2', label: 'SIRH' },
      { id: 's3', label: 'Formation' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-10',
    userId: 'user-10',
    fullName: 'Nadia El Fassi',
    title: 'Product Manager',
    city: 'Casablanca',
    country: 'Maroc',
    sector: 'Technologie',
    languages: ['Français', 'Anglais', 'Arabe'],
    availabilityStatus: 'disponible',
    whatsapp: '+212 6 12 34 56 78',
    contactEmail: 'nadia.elfassi@email.com',
    externalLink: 'https://nadiaelfassi.com',
    profileViewsCount: 367,
    publicUrlSlug: 'nadia-el-fassi',
    verified: true,
    completionPercent: 93,
    skills: [
      { id: 's1', label: 'Product Management' },
      { id: 's2', label: 'Agile/Scrum' },
      { id: 's3', label: 'UX Research' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-11',
    userId: 'user-11',
    fullName: 'Cheikh Omar Sarr',
    title: 'Expert Cybersécurité',
    city: 'Dakar',
    country: 'Sénégal',
    sector: 'Technologie',
    languages: ['Français', 'Anglais', 'Wolof'],
    availabilityStatus: 'en_veille',
    whatsapp: '+221 76 456 7890',
    contactEmail: 'cheikh.sarr@email.com',
    externalLink: 'https://github.com/cheikhsarr',
    profileViewsCount: 198,
    publicUrlSlug: 'cheikh-sarr',
    verified: false,
    completionPercent: 72,
    skills: [
      { id: 's1', label: 'Cybersécurité' },
      { id: 's2', label: 'Pentest' },
      { id: 's3', label: 'SIEM' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
  {
    id: 'prof-12',
    userId: 'user-12',
    fullName: 'Adama Coulibaly',
    title: 'Ingénieur Génie Civil',
    city: 'Ouagadougou',
    country: 'Burkina Faso',
    sector: 'BTP',
    languages: ['Français', 'Dioula'],
    availabilityStatus: 'disponible',
    whatsapp: '+226 70 12 34 56',
    contactEmail: 'adama.coulibaly@email.com',
    externalLink: '',
    profileViewsCount: 112,
    publicUrlSlug: 'adama-coulibaly',
    verified: true,
    completionPercent: 77,
    skills: [
      { id: 's1', label: 'Génie civil' },
      { id: 's2', label: 'Béton armé' },
      { id: 's3', label: 'Gestion de chantier' },
    ],
    experiences: [],
    education: [],
    publications: [],
  },
]

export const MOCK_VERIFICATION_REQUESTS: VerificationRequest[] = [
  {
    id: 'vr-1',
    type: 'experience',
    itemId: 'e1',
    itemTitle: 'Ingénieur Logiciel Senior — Orange Digital Center',
    profileName: 'Amadou Diallo',
    profileTitle: 'Ingénieur Logiciel Senior',
    institutionEmail: 'rh@orange.sn',
    status: 'en_attente',
    sentAt: '2026-06-10',
  },
  {
    id: 'vr-2',
    type: 'education',
    itemId: 'ed1',
    itemTitle: 'Master en Génie Informatique — École Polytechnique de Thiès',
    profileName: 'Fatou Ndiaye',
    profileTitle: 'Consultante Finance & Stratégie',
    institutionEmail: 'scolarite@ept.sn',
    status: 'en_attente',
    sentAt: '2026-06-12',
  },
  {
    id: 'vr-3',
    type: 'experience',
    itemId: 'e3',
    itemTitle: 'Chef de Projet — Banque de Dakar',
    profileName: 'Moussa Traoré',
    profileTitle: 'Data Scientist',
    institutionEmail: 'rh@banquededakar.sn',
    status: 'en_attente',
    sentAt: '2026-06-18',
  },
  {
    id: 'vr-4',
    type: 'education',
    itemId: 'ed2',
    itemTitle: 'Licence Droit — UCAD',
    profileName: 'Aïssatou Bah',
    profileTitle: 'Avocate en Droit des Affaires',
    institutionEmail: 'scolarite@ucad.edu.sn',
    status: 'confirmée',
    sentAt: '2026-05-20',
    resolvedAt: '2026-05-25',
  },
  {
    id: 'vr-5',
    type: 'experience',
    itemId: 'e5',
    itemTitle: 'Stagiaire RH — Total Énergie',
    profileName: 'Ibrahim Touré',
    profileTitle: 'Responsable RH',
    institutionEmail: 'rh@totalenergies.com',
    status: 'rejetée',
    sentAt: '2026-04-15',
    resolvedAt: '2026-04-22',
  },
]

export const MOCK_JOB_OFFERS: JobOffer[] = [
  {
    id: 'job-1',
    organizationId: 'org-1',
    title: 'Développeur Full Stack React/Node.js',
    description: 'Nous recherchons un développeur Full Stack expérimenté pour rejoindre notre équipe produit à Dakar.',
    location: 'Dakar, Sénégal',
    createdAt: '2026-06-20',
  },
  {
    id: 'job-2',
    organizationId: 'org-1',
    title: 'Responsable Marketing Digital',
    description: 'Pilotez notre stratégie de marketing digital en Afrique de l\'Ouest.',
    location: 'Abidjan, Côte d\'Ivoire',
    createdAt: '2026-06-15',
  },
]

export const SECTORS = [
  'Technologie',
  'Finance',
  'Santé',
  'Éducation',
  'Juridique',
  'Marketing',
  'Architecture',
  'Ressources Humaines',
  'BTP',
  'Agriculture',
  'Énergie',
  'Transport & Logistique',
  'Médias & Communication',
  'Consulting',
  'Entrepreneuriat',
]

export const COUNTRIES = [
  'Bénin', 'Burkina Faso', 'Cameroun', 'Côte d\'Ivoire',
  'France', 'Ghana', 'Guinée', 'Madagascar', 'Mali', 'Maroc',
  'Mauritanie', 'Niger', 'Nigéria', 'Sénégal', 'Togo', 'Tunisie',
]

export const LANGUAGES = [
  'Français', 'Anglais', 'Arabe', 'Wolof', 'Peul', 'Bambara',
  'Dioula', 'Éwé', 'Haoussa', 'Twi', 'Portugais', 'Pulaar',
]
